### ISSUE TITLE
MQTT secure connection

### ISSUE THREAD

**Issue by arilink** [mauricek/qtmqtt_cloud_connectors#1]
I have seen your project using MQTT to connect to Alibaba Cloud on forums and github. I also used QT to achieve similar operations, but Alibaba Cloud recommends using TLS for connection to ensure data security. I saw QT has more information about SSL but unable to connect normally, I want to ask for your help

**Comment by mauricek** [comment]
Hey, sorry for not replying earlier.
Qt Mqtt allows to specify a QAbstractSocket based transport channel. So you can specify your own with all TLS features set. Please check https://doc.qt.io/qt-6/qsslsocket.html

Hope it helps.
